package it.polimi.ingsw.GC_28.effects;

public enum EffectType {
	PRIVILEGESEFFECT, RESOURCEEFFECT, PRODUCTIONEFFECT, HARVESTEFFECT, EXCHANGEEFFECT, MULTIPLIEREFFECT, 
	DISCOUNTEFFECT, TAKECARDEFFECT, GOTOHP, NOCELLBONUS, INCREMENTCARDEFFECT, INCREMENTHPEFFECT,NOEFFECT,
	NOFINALBONUSEFFECT, OTHEREFFECT, SKIPROUNDEFFECT,NOMARKETEFFECT,REDUCEDICEEFFECT,
	FINALREDUCEEFFECT,SERVANTEFFECT,NOMILITARYFORTERRITORYEFFECT,FREESPACEEFFECT,NOEXTRACOSTINTOWEREFFECT,
	COINDISCOUNTEFFECT,DOUBLERESOURCEEFFECT,SETFAMILYMEMBERVALUEEFFECT,POPEEFFECT;
}

