package it.polimi.ingsw.GC_28.effects;

public enum EffectType {
	//cards effects
	PRIVILEGESEFFECT, RESOURCEEFFECT, PRODUCTIONEFFECT, HARVESTEFFECT, EXCHANGEEFFECT, MULTIPLIEREFFECT, 
	DISCOUNTEFFECT, TAKECARDEFFECT, GOTOHP, NOCELLBONUS, INCREMENTCARDEFFECT, INCREMENTHARVESTEFFECT,INCREMENTPRODUCTIONEFFECT, NOEFFECT,
	//excommunications effects
	NOFINALBONUSEFFECT, OTHEREFFECT, SKIPROUNDEFFECT,NOMARKETEFFECT,MODIFYDICEEFFECT,
	FINALREDUCEEFFECT,SERVANTEFFECT, 
	//leaders effects
	NOMILITARYFORTERRITORYEFFECT,FREESPACEEFFECT,NOEXTRACOSTINTOWEREFFECT,
	COINDISCOUNTEFFECT,DOUBLERESOURCEEFFECT,SETFAMILYMEMBERVALUEEFFECT,POPEEFFECT,COPYEFFECT;
}

