package effects;

public enum EffectType {
	PRIVILEGESEFFECT, RESOURCEEFFECT, PRODUCTIONEFFECT, HARVESTEFFECT, EXCHANGEEFFECT, MULTIPLIEREFFECT, 
	DISCOUNTEFFECT, TAKECARDEFFECT, GOTOHP, NOCELLBONUS,
	INCREMENTCARDEFFECT, INCREMENTHPEFFECT;
}

